### ISSUE TITLE
表情键盘功能

### ISSUE THREAD

**Issue by taojeff** [ZhipingYang/UUChatTableView#56]
博主，我表情键盘的添加如何能和你的那个functionInputView进行关联起来呢？能否提供一个思路或者将表情键盘功能也添加上去

**Comment by ZhipingYang** [comment]
表情键盘必须作为那个textfield的inputview，就可以了

**Comment by taojeff** [comment]
我刚刚也是这样做处理的 把表情键盘房子functionInputView页面里 然后点击到的表情字段放到textInput中，然后在点击发送的地方给self.btnContent 设置了一下attribute.可是这个时候我遇到了一个问题就是我点击表情键盘的按钮和文字输入按钮进行切换的时候发现没办法做到tableview的自动布局，就是在切换到表情键盘的时候这个时候tableview的高度是整个屏高，这样就造成了内容有被覆盖的问题。还有就是我在把我的富文本框内容给self.btnContent 接收的时候发现显示内容的cell貌似有问题宽度和高度都不能进行cgrect了

**Comment by ZhipingYang** [comment]
键盘frame变化的通知没有调？看看什么原因Sent from Mail Master
            在2016年08月24日 11:53，taojeff 写道:我刚刚也是这样做处理的 把表情键盘房子functionInputView页面里 然后点击到的表情字段放到textInput中，然后在点击发送的地方给self.btnContent 设置了一下attribute.可是这个时候我遇到了一个问题就是我点击表情键盘的按钮和文字输入按钮进行切换的时候发现没办法做到tableview的自动布局，就是在切换到表情键盘的时候这个时候tableview的高度是整个屏高，这样就造成了内容有被覆盖的问题。还有就是我在把我的富文本框内容给self.btnContent 接收的时候发现显示内容的cell貌似有问题宽度和高度都不能进行cgrect了

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ZhipingYang/UUChatTableView","title":"ZhipingYang/UUChatTableView","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ZhipingYang/UUChatTableView"}},"updates":{"snippets":[{"icon":"PERSON","message":"@taojeff in #56: 我刚刚也是这样做处理的 把表情键盘房子functionInputView页面里 然后点击到的表情字段放到textInput中，然后在点击发送的地方给self.btnContent 设置了一下attribute.可是这个时候我遇到了一个问题就是我点击表情键盘的按钮和文字输入按钮进行切换的时候发现没办法做到tableview的自动布局，就是在切换到表情键盘的时候这个时候tableview的高度是整个屏高，这样就造成了内容有被覆盖的问题。还有就是我在把我的富文本框内容给self.btnContent 接收的时候发现显示内容的cell貌似有问题宽度和高度都不能进行cgrect了"}],"action":{"name":"View Issue","url":"https://github.com/ZhipingYang/UUChatTableView/issues/56#issuecomment-241950649"}}}

**Comment by taojeff** [comment]
![1](https://cloud.githubusercontent.com/assets/19642626/17919375/9e1ab022-69ff-11e6-9e51-cd8597f1c27f.png)
![2](https://cloud.githubusercontent.com/assets/19642626/17919374/9e18b308-69ff-11e6-95a1-a3d639f52a68.png)
具体的截图如下 就是我在发送按钮和输入框这中间放了一个button按钮，通过按钮的是否选中来进行显示是否为表情按钮还是系统键盘按钮。也就是当我选中表情按钮的时候找个时候键盘的确是弹出来了，可是这个显示聊天信息的tableview并没有像弹出系统键盘那样进行自动更改高度，从而导致我的下面还有一部分的内容无法正常的显示出来。后来我又手动的进行修改tableview的高度后发现还是没有什么太明显的效果。所以我想问一下你，我如何进行两个键盘用一个通知进行管理与tableview之间的关联高度

**Comment by taojeff** [comment]
下面两个是我的表情按钮代码的截图和按钮通知的执行代码
![1](https://cloud.githubusercontent.com/assets/19642626/17919496/a1feda00-6a00-11e6-9ee9-52216b7e8d00.png)
![2](https://cloud.githubusercontent.com/assets/19642626/17919497/a1ffc294-6a00-11e6-9fde-0934caa63d1f.png)

**Comment by ZhipingYang** [comment]
用这个UIKeyboardDidChangeFrameNotification通知

**Comment by taojeff** [comment]
老大 能否加QQ进行私聊 因为有很多问题在这个上面请教你可能没那样详尽

**Comment by taojeff** [comment]
老大 好奇怪啊 我刚刚测试了一下表情功能 发现都是同样大小的图标为什么只有单独的两个图标它会计算不出来它的具体的高度呢
![simulator screen shot 2016 8 25 8 57 54](https://cloud.githubusercontent.com/assets/19642626/17969907/de450956-6b06-11e6-94e3-b5dee254364b.png)

**Comment by ZhipingYang** [comment]
具体的问题可能还是需要自己的解决了。

**Comment by taojeff** [comment]
楼主 我以上的问题都已经解决完毕 不过还是希望你能在你的项目上进一步的完善 这样我们大家也都能学习一下你的思路

**Comment by ZhipingYang** [comment]
OK 👌

**Comment by bidm** [comment]
taojeff   哥们儿  给个demo呗

**Comment by bidm** [comment]
@taojeff
